- name: backlog
  color: 7ef7ef
- name: blocked
  color: fc1423
- name: bug
  color: d73a4a
- name: chore
  color: ffffff
- name: ci
  color: 0075ca
- name: dependencies
  color: 276bd1
- name: discussion
  color: b6b1f9
- name: documentation
  color: 0075ca
- name: duplicate
  color: cfd3d7
- name: error handling
  color: 80c042
- name: feature request
  color: fcf95a
- name: good first issue
  color: 7057ff
- name: has pr
  color: 4b1f8e
- name: help wanted
  color: '008672'
- name: in progress
  color: ffccd7
- name: in review
  color: aed5fc
- name: invalid
  color: e4e669
- name: need repro
  color: c66037
- name: packages:console
  color: fbca04
- name: packages:create-petal
  color: fbca04
- name: packages:crypto
  color: fbca04
- name: packages:eslint
  color: fbca04
- name: packages:eslint-plugin
  color: fbca04
- name: packages:fetch
  color: fbca04
- name: packages:iterator
  color: fbca04
- name: packages:loader
  color: fbca04
- name: packages:metadata
  color: fbca04
- name: packages:node
  color: fbca04
- name: packages:result
  color: fbca04
- name: packages:scripts
  color: fbca04
- name: packages:store
  color: fbca04
- name: packages:types
  color: fbca04
- name: packages:typescript
  color: fbca04
- name: packages:utilities
  color: fbca04
- name: performance
  color: 80c042
- name: priority:high
  color: fc1423
- name: refactor
  color: 1d637f
- name: regression
  color: ea8785
- name: semver:major
  color: c10f47
- name: semver:minor
  color: e4f486
- name: semver:patch
  color: e8be8b
- name: tests
  color: f06dff
- name: typings
  color: 80c042
- name: utility
  color: 80c042
- name: wontfix
  color: ffffff
