name: Bug report
description: Report an issue with a Petal package.
labels: [bug, need repro]
body:
  - type: dropdown
    id: package
    attributes:
      label: Which package is this bug report for?
      options:
        - Console
        - create-petal
        - ESLint
        - ESLint Plugin
        - Fetch
        - Iterator
        - Loader
        - Metadata
        - Node Utilities
        - Result
        - Store
        - Types
        - TypeScript
        - Utilities
        - Documentation
    validations:
      required: true
  - type: textarea
    id: description
    attributes:
      label: Issue description
      description: Describe the issue in as much detail as possible.
      placeholder: |
        Steps to reproduce with below code sample:
        1. Do thing
        3. Observe behavior
        4. See error logs below
    validations:
      required: true
  - type: textarea
    id: code_sample
    attributes:
      label: Code sample
      description: |
        Your code sample should be:
        1. Minimal - Use as little code as possible that still produces the same problem (and is understandable)
        2. Complete - Provide all parts someone else needs to reproduce your problem
        3. Reproducible - Test the code you're about to provide to make sure it reproduces the problem

        This will be automatically formatted into code, so no need for backticks.
      render: typescript
  - type: textarea
    id: versions
    attributes:
      label: Versions
      description: Output of `pnpm dlx envinfo --system --binaries --browsers`
      placeholder: |
        - @flowr/utilities 4.12.1 (`npm ls @flowr/utilities` or another package)
        - Node.js 16.11.0 (`node --version`)
        - TypeScript 5.1.6 (`npm ls typescript` if you use it)
        - macOS Ventura 13.3.1
    validations:
      required: true
  - type: dropdown
    id: priority
    attributes:
      label: Issue priority
      description: Please be realistic. If you need to elaborate on your reasoning, please use the issue description field above.
      options:
        - Low (slightly annoying)
        - Medium (should be fixed soon)
        - High (immediate attention needed)
    validations:
      required: true
