name: Deprecate version
on:
  workflow_dispatch:
    inputs:
      package:
        description: Package
        required: true
        type: choice
        options:
          - '@flowr/console'
          - create-petal
          - '@flowr/eslint'
          - '@flowr/eslint-plugin'
          - '@flowr/fetch'
          - '@flowr/iterator'
          - '@flowr/loader'
          - '@flowr/metadata'
          - '@flowr/node'
          - '@flowr/result'
          - '@flowr/store'
          - '@flowr/types'
          - '@flowr/typescript'
          - '@flowr/utilities'
      version:
        description: Version(s)
        required: true
        type: string
      message:
        description: Deprecation message
        required: false
        type: string
jobs:
  deprecate:
    runs-on: ubuntu-latest
    if: github.repository_owner == 'pulseflow'
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install dependencies
        uses: ./packages/actions/src/pnpmCache

      - name: Deprecate
        run: pnpm exec npm-deprecate --name "${{inputs.version}}" --message "${{inputs.message || 'This version is deprecated. Please use a newer version.'}}" --package ${{inputs.package}}
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
