name: release

on:
  push:
    tags:
      - 'v*'

jobs:
  release:
    name: 'release: ubuntu-latest (node@lts/*)'
    permissions:
      id-token: write
      contents: write
    runs-on: ubuntu-latest
    steps:
      - name: disable git crlf
        run: |
          git config --global core.autocrlf false
          git config --global core.eol lf

      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: setup pnpm
        uses: pnpm/action-setup@v4

      - name: setup node
        uses: actions/setup-node@v4
        with:
          node-version: lts/*
          registry-url: 'https://registry.npmjs.org'

      - name: generate changelog
        run: pnpm dlx changelogithub
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: setup ni
        run: npm i -g @antfu/ni

      - name: install dependencies
        run: nci

      - name: build packages
        run: nr build

      - name: publish packages
        run: pnpm -r publish --access public --no-git-checks --provenance
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
          NPM_CONFIG_PROVENANCE: true
